### ISSUE TITLE
Query Parameters, Filters, etc

### ISSUE THREAD

**Issue by angelo0000** [groupdock/mongoose-nested-set#9]
Since folks use this as a way to lookup items in their tree, would it be possible for your finds (descendants, ancestors, etc) to support the same arguments as mongoose? 

Meaning instead of just descendants(callback) it would be descendants(filters, fields, options, callback)?

I added these features to the materialized path node module but it has limitations because of the key index limit in mongo and I'd like to move over to this approach as it works better for deeper trees.

**Comment by dambalah** [comment]
Done with https://github.com/groupdock/mongoose-nested-set/pull/11
